# version: "3.9"

services: 
  judge: 
    restart: always 
    build: 
      context: . 
      dockerfile: ./docker/dev/django/Dockerfile 
    volumes: 
        - /var/run/docker.sock:/var/run/docker.sock 
        # - /usr/bin/docker:/usr/bin/docker
        - .:/app:z 
        - judge_data:/app/data 
    ports:
        - "8000:8000"
    env_file: 
        - ./.envs/.dev/.django 
    command: /start 
    networks: 
        - judge-network 





networks:
  judge-network: 
    driver: bridge 

volumes:
  judge_data: 
    external: true 
